baseURL = "https://linnsofies.netlify.app/"
title = "Linn Sofie Sæther" # Site title.
theme = "hugo-coder" # Theme.
languageCode = "en" # Language used to generate RSS.
defaultContentLanguage = "en" # Default content language. 
paginate = 20 # Default number of pages per page in pagination.
ignoreFiles = ["\\.qmd$", "\\.ipynb$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "about\\.html", "static/blog/\\*_files/", "README"] 


[markup.highlight]
style = "manni"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      

[params]
author = "Linn Sofie Sæther" # Author's name. 
info = ["Neuroscientist & PhD candidate"] # Background information for author.
description = "Linn Sofie's personal website" # Site description.
keywords = "blog,personal,coding" # Site keywords. 
avatarURL = "images/IMG_1870.jpeg" # Path of avatar to display in static folder. 
since = 2023
dateFormat = "January 2, 2006"


hideCredits = true # Hides credits.
hideCopyright = true # Hides copyright.
colorScheme = "light" # Color scheme. 
hideColorSchemeToggle = true # Remove option for light/dark mode
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"


# Social links
[[params.social]]
name = "ResearchGate"
icon = "fa fa-2x fa-researchgate"
weight = 1
url = "https://researchgate.net/profile/Linn-Sofie-Saether/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/linnssaether/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/linnhub/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/linnssaether/"

[[params.social]]
name = "Instagram"
icon = "fa fa-2x fa-instagram"
weight = 5
url = "https://www.instagram.com/linnsofies/"


# Menu links
[[languages.en.menu.main]]
name = "blog"
weight = 1
url = "blog/"

[[languages.en.menu.main]]
name = "publications"
weight = 2
url = "publications/"

[[languages.en.menu.main]]
name = "about"
weight = 3
url = "about/"

[[languages.en.menu.main]]
name = "contact"
weight = 4
url = "contact/"





